name: Build & Deploy RippleWriter

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Render site
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          RIPPLEWRITER_MOCK: ${{ vars.RIPPLEWRITER_MOCK }}
        run: python render.py

      - name: Upload site artifact (output/)
        uses: actions/upload-pages-artifact@v3
        with:
          path: output   # <<<<<< publish output/ as the site root

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
