name: Build & Deploy RippleReports

on:
  push:
    branches: [ main ]
    paths:
      - 'articles/**'
      - 'templates/**'
      - 'render.py'
      - 'llm_client.py'
      - 'requirements.txt'
      - '.github/workflows/pages.yml'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Render posts
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          RIPPLEWRITER_MODEL: ${{ vars.RIPPLEWRITER_MODEL || 'gpt-4.1-mini' }}
        run: |
          python render.py
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./output

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4